disp("calculate_material_componet_values");

temp_eps_r = ones(1, size(material_type, 2));
temp_mu_r = ones(1, size(material_type, 2));
temp_sigma_e = zeros(1, size(material_type, 2));
temp_sigma_m = zeros(1, size(material_type, 2));

for i = 1:size(material_type, 2)
    temp_eps_r(i) = material_type(i).eps_r;
    temp_mu_r(i) = material_type(i).mu_r;
    temp_sigma_e(i) = material_type(i).sigma_e;
    temp_sigma_m(i) = material_type(i).sigma_m;
end

% avoid error: division by zero
temp_sigma_e(temp_sigma_e == 0) = 1e-20;
temp_sigma_m(temp_sigma_m == 0) = 1e-20;

% calculate x
% x轴上的eps_r == 1
eps_r_x(1:nx, 2:ny, 2:nz) = ...
0.25 * (temp_eps_r(material_3d_space(1:nx, 2:ny, 2:nz)) ...
    + temp_eps_r(material_3d_space(1:nx, 1:ny - 1, 2:nz)) ...
    + temp_eps_r(material_3d_space(1:nx, 2:ny, 1:nz - 1)) ...
    + temp_eps_r(material_3d_space(1:nx, 1:ny - 1, 1:nz - 1)));
mu_r_x(2:nx, 1:ny, 1:nz) = ...
    2 * (temp_mu_r(material_3d_space(2:nx, 1:ny, 1:nz)) ...
    .* temp_mu_r(material_3d_space(1:nx - 1, 1:ny, 1:nz))) ...
    ./ (temp_mu_r(material_3d_space(2:nx, 1:ny, 1:nz)) ...
    + temp_mu_r(material_3d_space(1:nx - 1, 1:ny, 1:nz)));
sigma_e_x(1:nx, 2:ny, 2:nz) = ...
    0.25 * (temp_sigma_e(material_3d_space(1:nx, 2:ny, 2:nz)) ...
    + temp_sigma_e(material_3d_space(1:nx, 1:ny - 1, 2:nz)) ...
    + temp_sigma_e(material_3d_space(1:nx, 2:ny, 1:nz - 1)) ...
    + temp_sigma_e(material_3d_space(1:nx, 1:ny - 1, 1:nz - 1)));
sigma_m_x(2:nx, 1:ny, 1:nz) = ...
    2 * (temp_sigma_m(material_3d_space(2:nx, 1:ny, 1:nz)) ...
    .* temp_sigma_m(material_3d_space(1:nx - 1, 1:ny, 1:nz))) ...
    ./ (temp_sigma_m(material_3d_space(2:nx, 1:ny, 1:nz)) ...
    + temp_sigma_m(material_3d_space(1:nx - 1, 1:ny, 1:nz)));

% calculate y
eps_r_y(2:nx, 1:ny, 2:nz) = ...
0.25 * (temp_eps_r(material_3d_space(2:nx, 1:ny, 2:nz)) ...
    + temp_eps_r(material_3d_space(1:nx - 1, 1:ny, 2:nz)) ...
    + temp_eps_r(material_3d_space(2:nx, 1:ny, 1:nz - 1)) ...
    + temp_eps_r(material_3d_space(1:nx - 1, 1:ny, 1:nz - 1)));
mu_r_y(1:nx, 2:ny, 1:nz) = ...
    2 * (temp_mu_r(material_3d_space(1:nx, 2:ny, 1:nz)) ...
    .* temp_mu_r(material_3d_space(1:nx, 1:ny - 1, 1:nz))) ...
    ./ (temp_mu_r(material_3d_space(1:nx, 2:ny, 1:nz)) ...
    + temp_mu_r(material_3d_space(1:nx, 1:ny - 1, 1:nz)));
sigma_e_y(2:nx, 1:ny, 2:nz) = ...
    0.25 * (temp_sigma_e(material_3d_space(2:nx, 1:ny, 2:nz)) ...
    + temp_sigma_e(material_3d_space(1:nx - 1, 1:ny, 2:nz)) ...
    + temp_sigma_e(material_3d_space(2:nx, 1:ny, 1:nz - 1)) ...
    + temp_sigma_e(material_3d_space(1:nx - 1, 1:ny, 1:nz - 1)));
sigma_m_y(1:nx, 2:ny, 1:nz) = ...
    2 * (temp_sigma_m(material_3d_space(1:nx, 2:ny, 1:nz)) ...
    .* temp_sigma_m(material_3d_space(1:nx, 1:ny - 1, 1:nz))) ...
    ./ (temp_sigma_m(material_3d_space(1:nx, 2:ny, 1:nz)) ...
    + temp_sigma_m(material_3d_space(1:nx, 1:ny - 1, 1:nz)));

% calculate z
eps_r_z(2:nx, 2:ny, 1:nz) = ...
0.25 * (temp_eps_r(material_3d_space(2:nx, 2:ny, 1:nz)) ...
    + temp_eps_r(material_3d_space(1:nx - 1, 2:ny, 1:nz)) ...
    + temp_eps_r(material_3d_space(2:nx, 1:ny - 1, 1:nz)) ...
    + temp_eps_r(material_3d_space(1:nx - 1, 1:ny - 1, 1:nz)));
mu_r_z(1:nx, 1:ny, 2:nz) = ...
    2 * (temp_mu_r(material_3d_space(1:nx, 1:ny, 2:nz)) ...
    .* temp_mu_r(material_3d_space(1:nx, 1:ny, 1:nz - 1))) ...
    ./ (temp_mu_r(material_3d_space(1:nx, 1:ny, 2:nz)) ...
    + temp_mu_r(material_3d_space(1:nx, 1:ny, 1:nz - 1)));
sigma_e_z(2:nx, 2:ny, 1:nz) = ...
    0.25 * (temp_sigma_e(material_3d_space(2:nx, 2:ny, 1:nz)) ...
    + temp_sigma_e(material_3d_space(1:nx - 1, 2:ny, 1:nz)) ...
    + temp_sigma_e(material_3d_space(2:nx, 1:ny - 1, 1:nz)) ...
    + temp_sigma_e(material_3d_space(1:nx - 1, 1:ny - 1, 1:nz)));
sigma_m_z(1:nx, 1:ny, 2:nz) = ...
    2 * (temp_sigma_m(material_3d_space(1:nx, 1:ny, 2:nz)) ...
    .* temp_sigma_m(material_3d_space(1:nx, 1:ny, 1:nz - 1))) ...
    ./ (temp_sigma_m(material_3d_space(1:nx, 1:ny, 2:nz)) ...
    + temp_sigma_m(material_3d_space(1:nx, 1:ny, 1:nz - 1)));
