current_time = current_time + dt / 2;

Ex(1:nx, 2:ny, 2:nz) = Cexe(1:nx, 2:ny, 2:nz) .* Ex(1:nx, 2:ny, 2:nz) ...
    + Cexhz(1:nx, 2:ny, 2:nz) .* (Hz(1:nx, 2:ny, 2:nz) - Hz(1:nx, 1:ny_n1, 2:nz)) ...
    + Cexhy(1:nx, 2:ny, 2:nz) .* (Hy(1:nx, 2:ny, 2:nz) - Hy(1:nx, 2:ny, 1:nz_n1));

Ey(2:nx, 1:ny, 2:nz) = Ceye(2:nx, 1:ny, 2:nz) .* Ey(2:nx, 1:ny, 2:nz) ...
    + Ceyhx(2:nx, 1:ny, 2:nz) .* (Hx(2:nx, 1:ny, 2:nz) - Hx(2:nx, 1:ny, 1:nz_n1)) ...
    + Ceyhz(2:nx, 1:ny, 2:nz) .* (Hz(2:nx, 1:ny, 2:nz) - Hz(1:nx_n1, 1:ny, 2:nz));

Ez(2:nx, 2:ny, 1:nz) = Ceze(2:nx, 2:ny, 1:nz) .* Ez(2:nx, 2:ny, 1:nz) ...
    + Cezhy(2:nx, 2:ny, 1:nz) .* (Hy(2:nx, 2:ny, 1:nz) - Hy(1:nx_n1, 2:ny, 1:nz)) ...
    + Cezhx(2:nx, 2:ny, 1:nz) .* (Hx(2:nx, 2:ny, 1:nz) - Hx(2:nx, 1:ny_n1, 1:nz));

if incident_plane_wave.enabled
    ixs = n_cpml_xn + 2;
    ixe = nx - n_cpml_xp;
    iys = n_cpml_yn + 2;
    iye = ny - n_cpml_yp;
    izs = n_cpml_yn + 2;
    ize = nz - n_cpml_zp;
    Ex(ixs:ixe, iys:iye, izs:ize) = Ex(ixs:ixe, iys:iye, izs:ize) +...
        Cexeic(ixs:ixe, iys:iye, izs:ize) .* Exic(ixs:ixe, iys:iye, izs:ize) +...
        Cexeip(ixs:ixe, iys:iye, izs:ize) .* Exip(ixs:ixe, iys:iye, izs:ize);
    Ey(ixs:ixe, iys:iye, izs:ize) = Ey(ixs:ixe, iys:iye, izs:ize) +...
        Ceyeic(ixs:ixe, iys:iye, izs:ize) .* Eyic(ixs:ixe, iys:iye, izs:ize) +...
        Ceyeip(ixs:ixe, iys:iye, izs:ize) .* Eyip(ixs:ixe, iys:iye, izs:ize);
    Ez(ixs:ixe, iys:iye, izs:ize) = Ez(ixs:ixe, iys:iye, izs:ize) +...
        Cezeic(ixs:ixe, iys:iye, izs:ize) .* Ezic(ixs:ixe, iys:iye, izs:ize) +...
        Cezeip(ixs:ixe, iys:iye, izs:ize) .* Ezip(ixs:ixe, iys:iye, izs:ize);
end
